eureka:
  client:
    service-url:
      defaultZone: http://eureka-7901:7901/eureka/
spring:
#  #zipkin
#  zipkin:
#    base-url: http://localhost:9411/
#    #采样比例1
#  sleuth:
#    sampler:
#      rate: 1
  application:
    name: consumer
  boot:
    admin:
      client:
        url: http://localhost:8080

server:
  port: 8088
---
server:
  port: 8088
spring:
  profiles: 8088
---
server:
  port: 8089
spring:
  profiles: 8089


ribbon:
  #连接超时时间(ms)
  ConnectTimeout: 1000
  #业务逻辑超时时间(ms)
  ReadTimeout: 2000
  #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetries: 3
  #重试负载均衡其他的实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 3
  #是否所有操作都重试
  ribbon.OkToRetryOnAllOperations: false
feign:
  hystrix:
    enabled: true
# http://localhost:8088/actuator/hystrix.stream 配置了才生效
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true
